//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Support: http://www.cnblogs.com/huxj
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace LuMei.LoLModel
{

	/// <summary>
	/// 实体类ChampionAbilities 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public partial class ChampionAbilities : Entity 
	{
		public ChampionAbilities():base("championAbilities") {}

		#region Model
		private int _Id;
		private int? _Rank;
		private int _ChampionId;
		private string _Name;
		private string _Cost;
		private string _Cooldown;
		private string _IconPath;
		private string _VideoPath;
		private decimal? _Range;
		private string _Effect;
		private string _Description;
		private string _Hotkey;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Rank
		{
			get{ return _Rank; }
			set
			{
				this.OnPropertyValueChange(_.Rank,_Rank,value);
				this._Rank=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int ChampionId
		{
			get{ return _ChampionId; }
			set
			{
				this.OnPropertyValueChange(_.ChampionId,_ChampionId,value);
				this._ChampionId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Cost
		{
			get{ return _Cost; }
			set
			{
				this.OnPropertyValueChange(_.Cost,_Cost,value);
				this._Cost=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Cooldown
		{
			get{ return _Cooldown; }
			set
			{
				this.OnPropertyValueChange(_.Cooldown,_Cooldown,value);
				this._Cooldown=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string IconPath
		{
			get{ return _IconPath; }
			set
			{
				this.OnPropertyValueChange(_.IconPath,_IconPath,value);
				this._IconPath=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string VideoPath
		{
			get{ return _VideoPath; }
			set
			{
				this.OnPropertyValueChange(_.VideoPath,_VideoPath,value);
				this._VideoPath=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? Range
		{
			get{ return _Range; }
			set
			{
				this.OnPropertyValueChange(_.Range,_Range,value);
				this._Range=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Effect
		{
			get{ return _Effect; }
			set
			{
				this.OnPropertyValueChange(_.Effect,_Effect,value);
				this._Effect=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Description
		{
			get{ return _Description; }
			set
			{
				this.OnPropertyValueChange(_.Description,_Description,value);
				this._Description=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Hotkey
		{
			get{ return _Hotkey; }
			set
			{
				this.OnPropertyValueChange(_.Hotkey,_Hotkey,value);
				this._Hotkey=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.Rank,
				_.ChampionId,
				_.Name,
				_.Cost,
				_.Cooldown,
				_.IconPath,
				_.VideoPath,
				_.Range,
				_.Effect,
				_.Description,
				_.Hotkey};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._Rank,
				this._ChampionId,
				this._Name,
				this._Cost,
				this._Cooldown,
				this._IconPath,
				this._VideoPath,
				this._Range,
				this._Effect,
				this._Description,
				this._Hotkey};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","championAbilities");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("id","championAbilities","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Rank = new Field("rank","championAbilities","rank");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ChampionId = new Field("championId","championAbilities","championId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("name","championAbilities","name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Cost = new Field("cost","championAbilities","cost");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Cooldown = new Field("cooldown","championAbilities","cooldown");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IconPath = new Field("iconPath","championAbilities","iconPath");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field VideoPath = new Field("videoPath","championAbilities","videoPath");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Range = new Field("range","championAbilities","range");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Effect = new Field("effect","championAbilities","effect");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Description = new Field("description","championAbilities","description");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Hotkey = new Field("hotkey","championAbilities","hotkey");
		}
		#endregion


	}
}

