//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Support: http://www.cnblogs.com/huxj
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace LuMei.LoLModel
{
    
	/// <summary>
    /// 英雄皮肤
	/// 实体类ChampionSkins 。(属性说明自动提取数据库字段的描述信息)\    /// 
	/// </summary>
	[Serializable]
	public partial class ChampionSkins : Entity 
	{
		public ChampionSkins():base("championSkins") {}

		#region Model
		private int _Id;
		private int? _IsBase;
		private int? _Rank;
		private int _ChampionId;
		private string _Name;
		private string _DisplayName;
		private string _PortraitPath;
		private string _SplashPath;
		private string _SwatchPath;
		private int? _IsFallback;
		private int? _FallbackIndex;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? IsBase
		{
			get{ return _IsBase; }
			set
			{
				this.OnPropertyValueChange(_.IsBase,_IsBase,value);
				this._IsBase=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Rank
		{
			get{ return _Rank; }
			set
			{
				this.OnPropertyValueChange(_.Rank,_Rank,value);
				this._Rank=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int ChampionId
		{
			get{ return _ChampionId; }
			set
			{
				this.OnPropertyValueChange(_.ChampionId,_ChampionId,value);
				this._ChampionId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string DisplayName
		{
			get{ return _DisplayName; }
			set
			{
				this.OnPropertyValueChange(_.DisplayName,_DisplayName,value);
				this._DisplayName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string PortraitPath
		{
			get{ return _PortraitPath; }
			set
			{
				this.OnPropertyValueChange(_.PortraitPath,_PortraitPath,value);
				this._PortraitPath=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string SplashPath
		{
			get{ return _SplashPath; }
			set
			{
				this.OnPropertyValueChange(_.SplashPath,_SplashPath,value);
				this._SplashPath=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string SwatchPath
		{
			get{ return _SwatchPath; }
			set
			{
				this.OnPropertyValueChange(_.SwatchPath,_SwatchPath,value);
				this._SwatchPath=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? IsFallback
		{
			get{ return _IsFallback; }
			set
			{
				this.OnPropertyValueChange(_.IsFallback,_IsFallback,value);
				this._IsFallback=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? FallbackIndex
		{
			get{ return _FallbackIndex; }
			set
			{
				this.OnPropertyValueChange(_.FallbackIndex,_FallbackIndex,value);
				this._FallbackIndex=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.IsBase,
				_.Rank,
				_.ChampionId,
				_.Name,
				_.DisplayName,
				_.PortraitPath,
				_.SplashPath,
				_.SwatchPath,
				_.IsFallback,
				_.FallbackIndex};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._IsBase,
				this._Rank,
				this._ChampionId,
				this._Name,
				this._DisplayName,
				this._PortraitPath,
				this._SplashPath,
				this._SwatchPath,
				this._IsFallback,
				this._FallbackIndex};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","championSkins");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("id","championSkins","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsBase = new Field("isBase","championSkins","isBase");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Rank = new Field("rank","championSkins","rank");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ChampionId = new Field("championId","championSkins","championId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("name","championSkins","name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DisplayName = new Field("displayName","championSkins","displayName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PortraitPath = new Field("portraitPath","championSkins","portraitPath");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SplashPath = new Field("splashPath","championSkins","splashPath");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SwatchPath = new Field("swatchPath","championSkins","swatchPath");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IsFallback = new Field("isFallback","championSkins","isFallback");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FallbackIndex = new Field("fallbackIndex","championSkins","fallbackIndex");
		}
		#endregion


	}
}

