//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Support: http://www.cnblogs.com/huxj
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace LuMei.LoLModel
{

	/// <summary>
	/// 英雄类型关联表
    /// 实体类ChampionSearchTags 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public partial class ChampionSearchTags : Entity 
	{
		public ChampionSearchTags():base("championSearchTags") {}

		#region Model
		private int _Id;
		private int _ChampionId;
		private int _SearchTagId;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int ChampionId
		{
			get{ return _ChampionId; }
			set
			{
				this.OnPropertyValueChange(_.ChampionId,_ChampionId,value);
				this._ChampionId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int SearchTagId
		{
			get{ return _SearchTagId; }
			set
			{
				this.OnPropertyValueChange(_.SearchTagId,_SearchTagId,value);
				this._SearchTagId=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.ChampionId,
				_.SearchTagId};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._ChampionId,
				this._SearchTagId};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","championSearchTags");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("id","championSearchTags","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ChampionId = new Field("championId","championSearchTags","championId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SearchTagId = new Field("searchTagId","championSearchTags","searchTagId");
		}
		#endregion


	}
}

