//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Support: http://www.cnblogs.com/huxj
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace LuMei.LoLModel
{

	/// <summary>
	/// 实体类Items 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public partial class Items : Entity 
	{
		public Items():base("items") {}

		#region Model
		private int _Id;
		private string _Name;
		private string _Description;
		private string _IconPath;
		private int? _Price;
		private decimal? _FlatHPPoolMod;
		private decimal? _FlatMPPoolMod;
		private decimal? _PercentHPPoolMod;
		private decimal? _PercentMPPoolMod;
		private decimal? _FlatHPRegenMod;
		private decimal? _PercentHPRegenMod;
		private decimal? _FlatMPRegenMod;
		private decimal? _PercentMPRegenMod;
		private decimal? _FlatArmorMod;
		private decimal? _PercentArmorMod;
		private decimal? _FlatAttackDamageMod;
		private decimal? _PercentAttackDamageMod;
		private decimal? _FlatAbilityPowerMod;
		private decimal? _PercentAbilityPowerMod;
		private decimal? _FlatMovementSpeedMod;
		private decimal? _PercentMovementSpeedMod;
		private decimal? _FlatAttackSpeedMod;
		private decimal? _PercentAttackSpeedMod;
		private decimal? _FlatDodgeMod;
		private decimal? _PercentDodgeMod;
		private decimal? _FlatCritChanceMod;
		private decimal? _PercentCritChanceMod;
		private decimal? _FlatCritDamageMod;
		private decimal? _PercentCritDamageMod;
		private decimal? _FlatMagicResistMod;
		private decimal? _PercentMagicResistMod;
		private decimal? _FlatEXPBonus;
		private decimal? _PercentEXPBonus;
		private int? _Epicness;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Description
		{
			get{ return _Description; }
			set
			{
				this.OnPropertyValueChange(_.Description,_Description,value);
				this._Description=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string IconPath
		{
			get{ return _IconPath; }
			set
			{
				this.OnPropertyValueChange(_.IconPath,_IconPath,value);
				this._IconPath=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Price
		{
			get{ return _Price; }
			set
			{
				this.OnPropertyValueChange(_.Price,_Price,value);
				this._Price=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? FlatHPPoolMod
		{
			get{ return _FlatHPPoolMod; }
			set
			{
				this.OnPropertyValueChange(_.FlatHPPoolMod,_FlatHPPoolMod,value);
				this._FlatHPPoolMod=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? FlatMPPoolMod
		{
			get{ return _FlatMPPoolMod; }
			set
			{
				this.OnPropertyValueChange(_.FlatMPPoolMod,_FlatMPPoolMod,value);
				this._FlatMPPoolMod=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? PercentHPPoolMod
		{
			get{ return _PercentHPPoolMod; }
			set
			{
				this.OnPropertyValueChange(_.PercentHPPoolMod,_PercentHPPoolMod,value);
				this._PercentHPPoolMod=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? PercentMPPoolMod
		{
			get{ return _PercentMPPoolMod; }
			set
			{
				this.OnPropertyValueChange(_.PercentMPPoolMod,_PercentMPPoolMod,value);
				this._PercentMPPoolMod=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? FlatHPRegenMod
		{
			get{ return _FlatHPRegenMod; }
			set
			{
				this.OnPropertyValueChange(_.FlatHPRegenMod,_FlatHPRegenMod,value);
				this._FlatHPRegenMod=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? PercentHPRegenMod
		{
			get{ return _PercentHPRegenMod; }
			set
			{
				this.OnPropertyValueChange(_.PercentHPRegenMod,_PercentHPRegenMod,value);
				this._PercentHPRegenMod=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? FlatMPRegenMod
		{
			get{ return _FlatMPRegenMod; }
			set
			{
				this.OnPropertyValueChange(_.FlatMPRegenMod,_FlatMPRegenMod,value);
				this._FlatMPRegenMod=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? PercentMPRegenMod
		{
			get{ return _PercentMPRegenMod; }
			set
			{
				this.OnPropertyValueChange(_.PercentMPRegenMod,_PercentMPRegenMod,value);
				this._PercentMPRegenMod=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? FlatArmorMod
		{
			get{ return _FlatArmorMod; }
			set
			{
				this.OnPropertyValueChange(_.FlatArmorMod,_FlatArmorMod,value);
				this._FlatArmorMod=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? PercentArmorMod
		{
			get{ return _PercentArmorMod; }
			set
			{
				this.OnPropertyValueChange(_.PercentArmorMod,_PercentArmorMod,value);
				this._PercentArmorMod=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? FlatAttackDamageMod
		{
			get{ return _FlatAttackDamageMod; }
			set
			{
				this.OnPropertyValueChange(_.FlatAttackDamageMod,_FlatAttackDamageMod,value);
				this._FlatAttackDamageMod=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? PercentAttackDamageMod
		{
			get{ return _PercentAttackDamageMod; }
			set
			{
				this.OnPropertyValueChange(_.PercentAttackDamageMod,_PercentAttackDamageMod,value);
				this._PercentAttackDamageMod=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? FlatAbilityPowerMod
		{
			get{ return _FlatAbilityPowerMod; }
			set
			{
				this.OnPropertyValueChange(_.FlatAbilityPowerMod,_FlatAbilityPowerMod,value);
				this._FlatAbilityPowerMod=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? PercentAbilityPowerMod
		{
			get{ return _PercentAbilityPowerMod; }
			set
			{
				this.OnPropertyValueChange(_.PercentAbilityPowerMod,_PercentAbilityPowerMod,value);
				this._PercentAbilityPowerMod=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? FlatMovementSpeedMod
		{
			get{ return _FlatMovementSpeedMod; }
			set
			{
				this.OnPropertyValueChange(_.FlatMovementSpeedMod,_FlatMovementSpeedMod,value);
				this._FlatMovementSpeedMod=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? PercentMovementSpeedMod
		{
			get{ return _PercentMovementSpeedMod; }
			set
			{
				this.OnPropertyValueChange(_.PercentMovementSpeedMod,_PercentMovementSpeedMod,value);
				this._PercentMovementSpeedMod=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? FlatAttackSpeedMod
		{
			get{ return _FlatAttackSpeedMod; }
			set
			{
				this.OnPropertyValueChange(_.FlatAttackSpeedMod,_FlatAttackSpeedMod,value);
				this._FlatAttackSpeedMod=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? PercentAttackSpeedMod
		{
			get{ return _PercentAttackSpeedMod; }
			set
			{
				this.OnPropertyValueChange(_.PercentAttackSpeedMod,_PercentAttackSpeedMod,value);
				this._PercentAttackSpeedMod=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? FlatDodgeMod
		{
			get{ return _FlatDodgeMod; }
			set
			{
				this.OnPropertyValueChange(_.FlatDodgeMod,_FlatDodgeMod,value);
				this._FlatDodgeMod=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? PercentDodgeMod
		{
			get{ return _PercentDodgeMod; }
			set
			{
				this.OnPropertyValueChange(_.PercentDodgeMod,_PercentDodgeMod,value);
				this._PercentDodgeMod=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? FlatCritChanceMod
		{
			get{ return _FlatCritChanceMod; }
			set
			{
				this.OnPropertyValueChange(_.FlatCritChanceMod,_FlatCritChanceMod,value);
				this._FlatCritChanceMod=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? PercentCritChanceMod
		{
			get{ return _PercentCritChanceMod; }
			set
			{
				this.OnPropertyValueChange(_.PercentCritChanceMod,_PercentCritChanceMod,value);
				this._PercentCritChanceMod=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? FlatCritDamageMod
		{
			get{ return _FlatCritDamageMod; }
			set
			{
				this.OnPropertyValueChange(_.FlatCritDamageMod,_FlatCritDamageMod,value);
				this._FlatCritDamageMod=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? PercentCritDamageMod
		{
			get{ return _PercentCritDamageMod; }
			set
			{
				this.OnPropertyValueChange(_.PercentCritDamageMod,_PercentCritDamageMod,value);
				this._PercentCritDamageMod=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? FlatMagicResistMod
		{
			get{ return _FlatMagicResistMod; }
			set
			{
				this.OnPropertyValueChange(_.FlatMagicResistMod,_FlatMagicResistMod,value);
				this._FlatMagicResistMod=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? PercentMagicResistMod
		{
			get{ return _PercentMagicResistMod; }
			set
			{
				this.OnPropertyValueChange(_.PercentMagicResistMod,_PercentMagicResistMod,value);
				this._PercentMagicResistMod=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? FlatEXPBonus
		{
			get{ return _FlatEXPBonus; }
			set
			{
				this.OnPropertyValueChange(_.FlatEXPBonus,_FlatEXPBonus,value);
				this._FlatEXPBonus=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? PercentEXPBonus
		{
			get{ return _PercentEXPBonus; }
			set
			{
				this.OnPropertyValueChange(_.PercentEXPBonus,_PercentEXPBonus,value);
				this._PercentEXPBonus=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Epicness
		{
			get{ return _Epicness; }
			set
			{
				this.OnPropertyValueChange(_.Epicness,_Epicness,value);
				this._Epicness=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.Name,
				_.Description,
				_.IconPath,
				_.Price,
				_.FlatHPPoolMod,
				_.FlatMPPoolMod,
				_.PercentHPPoolMod,
				_.PercentMPPoolMod,
				_.FlatHPRegenMod,
				_.PercentHPRegenMod,
				_.FlatMPRegenMod,
				_.PercentMPRegenMod,
				_.FlatArmorMod,
				_.PercentArmorMod,
				_.FlatAttackDamageMod,
				_.PercentAttackDamageMod,
				_.FlatAbilityPowerMod,
				_.PercentAbilityPowerMod,
				_.FlatMovementSpeedMod,
				_.PercentMovementSpeedMod,
				_.FlatAttackSpeedMod,
				_.PercentAttackSpeedMod,
				_.FlatDodgeMod,
				_.PercentDodgeMod,
				_.FlatCritChanceMod,
				_.PercentCritChanceMod,
				_.FlatCritDamageMod,
				_.PercentCritDamageMod,
				_.FlatMagicResistMod,
				_.PercentMagicResistMod,
				_.FlatEXPBonus,
				_.PercentEXPBonus,
				_.Epicness};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._Name,
				this._Description,
				this._IconPath,
				this._Price,
				this._FlatHPPoolMod,
				this._FlatMPPoolMod,
				this._PercentHPPoolMod,
				this._PercentMPPoolMod,
				this._FlatHPRegenMod,
				this._PercentHPRegenMod,
				this._FlatMPRegenMod,
				this._PercentMPRegenMod,
				this._FlatArmorMod,
				this._PercentArmorMod,
				this._FlatAttackDamageMod,
				this._PercentAttackDamageMod,
				this._FlatAbilityPowerMod,
				this._PercentAbilityPowerMod,
				this._FlatMovementSpeedMod,
				this._PercentMovementSpeedMod,
				this._FlatAttackSpeedMod,
				this._PercentAttackSpeedMod,
				this._FlatDodgeMod,
				this._PercentDodgeMod,
				this._FlatCritChanceMod,
				this._PercentCritChanceMod,
				this._FlatCritDamageMod,
				this._PercentCritDamageMod,
				this._FlatMagicResistMod,
				this._PercentMagicResistMod,
				this._FlatEXPBonus,
				this._PercentEXPBonus,
				this._Epicness};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","items");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("id","items","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("name","items","name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Description = new Field("description","items","description");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IconPath = new Field("iconPath","items","iconPath");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Price = new Field("price","items","price");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FlatHPPoolMod = new Field("flatHPPoolMod","items","flatHPPoolMod");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FlatMPPoolMod = new Field("flatMPPoolMod","items","flatMPPoolMod");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PercentHPPoolMod = new Field("percentHPPoolMod","items","percentHPPoolMod");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PercentMPPoolMod = new Field("percentMPPoolMod","items","percentMPPoolMod");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FlatHPRegenMod = new Field("flatHPRegenMod","items","flatHPRegenMod");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PercentHPRegenMod = new Field("percentHPRegenMod","items","percentHPRegenMod");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FlatMPRegenMod = new Field("flatMPRegenMod","items","flatMPRegenMod");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PercentMPRegenMod = new Field("percentMPRegenMod","items","percentMPRegenMod");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FlatArmorMod = new Field("flatArmorMod","items","flatArmorMod");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PercentArmorMod = new Field("percentArmorMod","items","percentArmorMod");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FlatAttackDamageMod = new Field("flatAttackDamageMod","items","flatAttackDamageMod");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PercentAttackDamageMod = new Field("percentAttackDamageMod","items","percentAttackDamageMod");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FlatAbilityPowerMod = new Field("flatAbilityPowerMod","items","flatAbilityPowerMod");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PercentAbilityPowerMod = new Field("percentAbilityPowerMod","items","percentAbilityPowerMod");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FlatMovementSpeedMod = new Field("flatMovementSpeedMod","items","flatMovementSpeedMod");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PercentMovementSpeedMod = new Field("percentMovementSpeedMod","items","percentMovementSpeedMod");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FlatAttackSpeedMod = new Field("flatAttackSpeedMod","items","flatAttackSpeedMod");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PercentAttackSpeedMod = new Field("percentAttackSpeedMod","items","percentAttackSpeedMod");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FlatDodgeMod = new Field("flatDodgeMod","items","flatDodgeMod");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PercentDodgeMod = new Field("percentDodgeMod","items","percentDodgeMod");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FlatCritChanceMod = new Field("flatCritChanceMod","items","flatCritChanceMod");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PercentCritChanceMod = new Field("percentCritChanceMod","items","percentCritChanceMod");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FlatCritDamageMod = new Field("flatCritDamageMod","items","flatCritDamageMod");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PercentCritDamageMod = new Field("percentCritDamageMod","items","percentCritDamageMod");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FlatMagicResistMod = new Field("flatMagicResistMod","items","flatMagicResistMod");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PercentMagicResistMod = new Field("percentMagicResistMod","items","percentMagicResistMod");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FlatEXPBonus = new Field("flatEXPBonus","items","flatEXPBonus");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PercentEXPBonus = new Field("percentEXPBonus","items","percentEXPBonus");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Epicness = new Field("epicness","items","epicness");
		}
		#endregion


	}
}

