//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Support: http://www.cnblogs.com/huxj
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace LuMei.LoLModel
{

	/// <summary>
	/// 实体类ItemRecipes 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public partial class ItemRecipes : Entity 
	{
		public ItemRecipes():base("itemRecipes") {}

		#region Model
		private int _Id;
		private int _RecipeItemId;
		private int _BuildsToItemId;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int RecipeItemId
		{
			get{ return _RecipeItemId; }
			set
			{
				this.OnPropertyValueChange(_.RecipeItemId,_RecipeItemId,value);
				this._RecipeItemId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int BuildsToItemId
		{
			get{ return _BuildsToItemId; }
			set
			{
				this.OnPropertyValueChange(_.BuildsToItemId,_BuildsToItemId,value);
				this._BuildsToItemId=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.RecipeItemId,
				_.BuildsToItemId};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._RecipeItemId,
				this._BuildsToItemId};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","itemRecipes");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("id","itemRecipes","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RecipeItemId = new Field("recipeItemId","itemRecipes","recipeItemId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field BuildsToItemId = new Field("buildsToItemId","itemRecipes","buildsToItemId");
		}
		#endregion


	}
}

