//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Support: http://www.cnblogs.com/huxj
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace LuMei.LoLModel
{

	/// <summary>
	/// 实体类ItemItemCategories 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public partial class ItemItemCategories : Entity 
	{
		public ItemItemCategories():base("itemItemCategories") {}

		#region Model
		private int _Id;
		private int _ItemId;
		private int _ItemCategoryId;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int ItemId
		{
			get{ return _ItemId; }
			set
			{
				this.OnPropertyValueChange(_.ItemId,_ItemId,value);
				this._ItemId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int ItemCategoryId
		{
			get{ return _ItemCategoryId; }
			set
			{
				this.OnPropertyValueChange(_.ItemCategoryId,_ItemCategoryId,value);
				this._ItemCategoryId=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.ItemId,
				_.ItemCategoryId};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._ItemId,
				this._ItemCategoryId};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","itemItemCategories");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("id","itemItemCategories","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ItemId = new Field("itemId","itemItemCategories","itemId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ItemCategoryId = new Field("itemCategoryId","itemItemCategories","itemCategoryId");
		}
		#endregion


	}
}

