//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Support: http://www.cnblogs.com/huxj
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace LuMei.LoLModel
{

	/// <summary>
	/// 实体类KeybindingEvents 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public partial class KeybindingEvents : Entity 
	{
		public KeybindingEvents():base("keybindingEvents") {}

		#region Model
		private int _Id;
		private string _InternalName;
		private string _DisplayName;
		private string _Bindings;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string InternalName
		{
			get{ return _InternalName; }
			set
			{
				this.OnPropertyValueChange(_.InternalName,_InternalName,value);
				this._InternalName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string DisplayName
		{
			get{ return _DisplayName; }
			set
			{
				this.OnPropertyValueChange(_.DisplayName,_DisplayName,value);
				this._DisplayName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Bindings
		{
			get{ return _Bindings; }
			set
			{
				this.OnPropertyValueChange(_.Bindings,_Bindings,value);
				this._Bindings=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.InternalName,
				_.DisplayName,
				_.Bindings};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._InternalName,
				this._DisplayName,
				this._Bindings};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","keybindingEvents");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("id","keybindingEvents","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field InternalName = new Field("internalName","keybindingEvents","internalName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DisplayName = new Field("displayName","keybindingEvents","displayName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Bindings = new Field("bindings","keybindingEvents","bindings");
		}
		#endregion


	}
}

