//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Support: http://www.cnblogs.com/huxj
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace LuMei.LoLModel
{

	/// <summary>
	/// 实体类WardSkins 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public partial class WardSkins : Entity 
	{
		public WardSkins():base("wardSkins") {}

		#region Model
		private int _Id;
		private string _Name;
		private string _IconUrl;
		private string _WardImageUrl;
		private string _HeroImageUrl;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string IconUrl
		{
			get{ return _IconUrl; }
			set
			{
				this.OnPropertyValueChange(_.IconUrl,_IconUrl,value);
				this._IconUrl=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string WardImageUrl
		{
			get{ return _WardImageUrl; }
			set
			{
				this.OnPropertyValueChange(_.WardImageUrl,_WardImageUrl,value);
				this._WardImageUrl=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string HeroImageUrl
		{
			get{ return _HeroImageUrl; }
			set
			{
				this.OnPropertyValueChange(_.HeroImageUrl,_HeroImageUrl,value);
				this._HeroImageUrl=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.Name,
				_.IconUrl,
				_.WardImageUrl,
				_.HeroImageUrl};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._Name,
				this._IconUrl,
				this._WardImageUrl,
				this._HeroImageUrl};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","wardSkins");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("id","wardSkins","id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("name","wardSkins","name");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IconUrl = new Field("iconUrl","wardSkins","iconUrl");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field WardImageUrl = new Field("wardImageUrl","wardSkins","wardImageUrl");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field HeroImageUrl = new Field("heroImageUrl","wardSkins","heroImageUrl");
		}
		#endregion


	}
}

